### ISSUE TITLE
add .d.ts and get to work as a imported package

### ISSUE THREAD

**Issue by cris691** [cris691/stubdb#8]
I can't seem to get the package to be seen as 'typed' by tsc when used as an import.

**Comment by cris691** [comment]
No idea how.

**Comment by vrMars** [comment]
Any updates on this?

**Comment by vrMars** [comment]
> Any updates on this?

Actually, just renaming "stubdb" to "sirdb" does the trick in the index.d.ts file.

**Comment by c9fe** [comment]
Thank you!
